
services:
  # Angular development server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "4200:4200"  # Direct access to Angular dev server
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./angular.json:/app/angular.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./tsconfig.spec.json:/app/tsconfig.spec.json:ro
      # Mount proxy configuration
      - ./proxy.conf.json:/app/proxy.conf.json:ro
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - backend

  # Python backend API
  weird-bench-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"  # Direct access to API for development
    volumes:
      # Mount backend code for hot reloading
      - ./backend:/app/backend:ro
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount schemas directory
      - ./schemas:/app/schemas:ro
    environment:
      - DATA_DIR=/app/data
      - DATABASE_URL=sqlite+aiosqlite:///app/data/benchmarks.db
      - PYTHONPATH=/app/backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local